config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :user do
    unauthenticated :user do
      root 'front#index', as: :front_page
    end

    authenticated :user do
      root 'homeworks#index', as: :authenticated_user_root
    end
  end

  get 'choose', to: 'choose_registration#new', as: :choose_registration
  post 'conekta_oxxo_pay' => 'oxxo_pay#received'

  resources :consultor_onboarding, only: [:new, :update], path_names: { new: 'first_step' } do
    member do
      post :add_accounts
    end
    collection do
      get :second_step
      get :third_step
      get :fourth_step
    end
  end
  resources :onboarding, except: [:index, :edit, :destroy], path_names: { new: 'first_step' } do
    member do
      get :second_step
      get :fourth_step
      get :fifth_step
      get :sixth_step
      patch :set_main_image
    end
  end
  resources :homeworks do
    member do
      post :process_payment
      put :publish
      delete :unpublish
    end
    resources :requests do
      resources :messages, only: :create
      member do
        post :accept
      end
    end
    resources :documents, only: [:index, :new, :create]
    resources :approvals, only: [:new, :create]
  end
  resources :cards, except: [:show, :edit, :update] do
    member do
      patch :make_default
    end
  end
  resources :bank_transfers, only: [:new, :create]
  resources :accounts, except: [:show, :index]

  mount LetterOpenerWeb::Engine, at: '/mails' if Rails.env.staging? || Rails.env.development?
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'

  root to: 'front#index'
end

app/controllers/front_controller.rb
# frozen_string_literal: true

class FrontController < ApplicationController
  layout 'homepage/application'

  def index; end
end

app/helpers/front_helper.rb
# frozen_string_literal: true

module FrontHelper
end

app/views/front/index.html.haml
%nav.navbar.nav-down{"data-animation" => "shrink", "data-fullwidth" => "true", "data-menu-style" => "light"}
  / Styles: light, dark, transparent, transparent-to-dark | Animation: hiding, shrink
  .container
    .navbar-header
      .container
        %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar.top-bar
          %span.icon-bar.middle-bar
          %span.icon-bar.bottom-bar
        %a.navbar-brand.to-top{:href => "#"}
        = image_tag 'estudex_logo.png', class: 'logo-light', style: 'width: 200px;'
    #navbar.navbar-collapse.collapse
      .container
        %ul.nav.navbar-nav.menu-right
          / Each section must have corresponding ID ( #hero -> id="hero" )
          %li
            %a{:href => "#hero"} Inicio
          %li
            %a{:href => "#about"} Acerca
          %li.nav-separator
          %li.nav-icon
            - if current_user
              = link_to 'Dashboard', homeworks_path
            - else
              = link_to 'Login', new_user_session_path

%section#hero.hero-fullscreen.parallax{"data-overlay-dark" => "7"}
  = image_tag 'backgrounds/school.jpg', class: 'background-image'
  .container
    .row
      .hero-content-slider.mt20{"data-autoplay" => "true", "data-speed" => "4000"}
        %div
          %h1
            Somos Estudex
            %br/
            %strong La aplicación que los estudiantes aman
          %p.lead Contacta a miles de expertos para hacer tus tareas profesionalmente y a un precio accesible
          %a.btn.btn-lg.btn-primary.btn-scroll{:href => "#about"} Registrate
        %div
          %h1
            Haz dinero
            %br/
            %strong Compartiendo tu conocimiento y ayudando
          %p.lead Desde la comodidad de tu casa, elige solo las tareas de los temas que más amas.
        %div
          %h1
            Elige a los mejores
            %br/
            %strong Con nuestro sistema de evaluación
          %p.lead Todos los usuarios pueden ver la reputación de los consultores y escoger al más apto.

%section#about.pt100.pb90
  .container
    .row
      .col-md-12.text-center.pb20
        %h2
          Somos Estudex
          %br/
          %strong Obten ayuda con tus tareas por parte de un profesional
        %p.lead
          Te invitamos a usar la aplicación
          = succeed "" do
            %span.color y conocer los beneficios
          = succeed "" do
            %br/
      .col-sm-6.feature-left
        .feature-left-content
          %h4
            %strong Rapidez y eficiencia
            = succeed "Las 24 horas del día" do
              %br/
          %p Miles de expertos en todas las ramas de estudio al alcance de un click, dispuestos a hacer tus tareas.
      .col-sm-6.feature-left
        .feature-left-content
          %h4
            %strong Bajos costos
            = succeed "Promociones" do
              %br/
          %p Precios muy accesibles, además te regalaremos $50 pesos por cada amigo que invites y compre una tarea de mínimo $100 pesos.
      .col-sm-6.feature-left
        .feature-left-content
          %h4
            %strong El mejor Servicio
            = succeed "Evaluación constante" do
              %br/
          %p Cuéntanos cómo te atendieron. En esta plataforma siempre recomendamos a los mejores consultores de tareas
      .col-sm-6.feature-left
        .feature-left-content
          %h4
            %strong Trabaja con nosotros
            = succeed "como Consultor " do
              %br/
          %p Tan fácil como registrarte y subir los documentos que acredíten tu último grado de estudios (título, cédula, certificados, etc.)

%section#who-we-are.parallax.pt40.pb40{"data-overlay-dark" => "8"}
  .background-image
    = image_tag 'backgrounds/school.jpg'
  .container
    .row.vertical-align
      .col-md-6.pr30.mt40.mb40
        %h2
          %strong Nuestros métricos actuales
          %br/
          %span.color Evaluamos a nuestros consultores y a nosotros mismos por cada tarea
        %p Esto mantiene a nuestros consultores motivados a ser mejores en cada entrega
        %p Si algo no te gusta, puedes agregarle un comentario al consultor o a la aplicación y respetaremos tu libertad de expresión. Evalúa el desempeño de la App por medio de indicadores clave: Entrega en tiempo, Calificación obtenida en la tarea, Calidad de la tarea, Prestigio
      .col-md-6.pt40.pb30
        .progress-bars.standard.transparent-bars{"data-animate-on-scroll" => "on"}
          %h5.bold Entregas en tiempo
          .progress{"data-percent" => "95%"}
            .progress-bar
              %span.progress-bar-tooltip 95%
          %h5.bold Calificación promedio obtenida
          .progress{"data-percent" => "98%"}
            .progress-bar.progress-bar-primary
              %span.progress-bar-tooltip 98%
          %h5.bold Calidad de la tarea
          .progress{"data-percent" => "97%"}
            .progress-bar.progress-bar-primary
              %span.progress-bar-tooltip 97%
          %h5.bold Prestigio
          .progress{"data-percent" => "92%"}
            .progress-bar.progress-bar-primary
              %span.progress-bar-tooltip 92%

%section#fun-facts{"data-animate" => "true"}
  .container-fluid
    .row
      .col-sm-3.counter
        %h1.bold{"data-count" => "2709"}
        %h5 Usuarios Registrados
      .col-sm-3.counter
        %h1.bold{"data-count" => "4905"}
        %h5 Consultores disponibles
      .col-sm-3.counter
        %h1.bold{"data-count" => "3709"}
        %h5 Tareas entregadas
      .col-sm-3.counter
        %h1.bold{"data-count" => "6837"}
        %h5 "Me gusta"

%section#services.pt100.pb90
  .container
    .row
      .col-md-12.text-center.pb20
        %h2
          Apoyo en cientos de temas de estudio
          %br/
          %strong en una sola plataforma:
        %p.lead
          /%strong Estudex:
          = succeed "" do
            %span.color
      .col-md-4.col-sm-6.feature-left
        .feature-left-content
          %h4
            %strong Ingeniería
            = succeed "Por Ejemplo:" do
              %br/
          %p Matemáticas, CAD, Electrónica, Programación, Mecánica, Control, Problemarios, etc
          /%p Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt
      .col-md-4.col-sm-6.feature-left
        .feature-left-content
          %h4
            %strong Administración
            = succeed "Por Ejemplo" do
              %br/
          %p Fundamentos de Administración, Marketing, Proyectos, Sociales, Recursos Humanos, etc.
      .col-md-4.col-sm-6.feature-left
        .feature-left-content
          %h4
            %strong Diseño y Arquitectura
            = succeed "Por Ejemplo" do
              %br/
          %p Logos, Creación de marcas, diseño web, posters, portadas, Fotoshop, Autocad, Mapas, etc
      .col-md-4.col-sm-6.feature-left
        .feature-left-content
          %h4
            %strong Economía y Finanzas
            = succeed "Por Ejemplo" do
              %br/
          %p Análisis financieros, presupuestos, reportes, planeación, investigaciónes, asesoría, etc.
      .col-md-4.col-sm-6.feature-left
        .feature-left-content
          %h4
            %strong Ciencias de la Salud
            = succeed "Por Ejemplo" do
              %br/
          %p Nutrición, Medicina, Psicología, Biotecnología, fisoterapia, enferemería, veterinaria, etc.
      .col-md-4.col-sm-6.feature-left
        .feature-left-content
          %h4
            %strong Y más...
            = succeed "Por Ejemplo" do
              %br/
          %p Reportes de Lectura, Ensayos, Protocolos, Investigaciónes, ediciones, presentaciones, etc

%section.parallax.pt110.pb70{"data-overlay-dark" => "8"}
  .container
    .row
      .col-md-12.details.white.text-center
        .phone-number.mb10
          %h1.bold Registrate

%section#contact.pt120.pb100
  .container
    .row
      .col-md-12.text-center.pb20
        %h2
          Comunicate
          %br/
          %strong Ponte en contacto
        %p.lead
          Queremos conocer tu opinion, pues es
          %span.color es muy importante
      .col-md-8.col-md-offset-2.contact.box-style
        #message-info
        / Forms can be functional only on server. Upload to your server when testing.
        %form#contactform{:method => "post"}
          .col-sm-12
            %input#name{:name => "name", :placeholder => "Nombre *"}/
          .col-sm-6
            %input#email{:name => "email", :placeholder => "Email *"}/
          .col-sm-6
            %input#phone{:name => "phone", :placeholder => "Teléfono"}/
          .col-sm-12
            %textarea#message{:name => "message", :placeholder => "Mensaje *", :rows => "9"}
          .col-md-12
            %input#submit.submit.btn.btn-lg.btn-primary{:type => "submit", :value => "Enviar"}/