config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :user do
    unauthenticated :user do
      root 'front#index', as: :front_page
    end

    authenticated :user do
      root 'homeworks#index', as: :authenticated_user_root
    end
  end

  get 'choose', to: 'choose_registration#new', as: :choose_registration
  post 'conekta_oxxo_pay' => 'oxxo_pay#received'

  resources :consultor_onboarding, only: [:new, :update], path_names: { new: 'first_step' } do
    member do
      post :add_accounts
    end
    collection do
      get :second_step
      get :third_step
      get :fourth_step
    end
  end
  resources :onboarding, except: [:index, :edit, :destroy], path_names: { new: 'first_step' } do
    member do
      get :second_step
      get :fourth_step
      get :fifth_step
      get :sixth_step
      patch :set_main_image
    end
  end
  resources :homeworks do
    member do
      post :process_payment
      put :publish
      delete :unpublish
    end
    resources :requests do
      resources :messages, only: :create
      member do
        post :accept
      end
    end
    resources :documents, only: [:index, :new, :create]
    resources :approvals, only: [:new, :create]
  end
  resources :cards, except: [:show, :edit, :update] do
    member do
      patch :make_default
    end
  end
  resources :bank_transfers, only: [:new, :create]
  resources :accounts, except: [:show, :index]

  mount LetterOpenerWeb::Engine, at: '/mails' if Rails.env.staging? || Rails.env.development?
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'

  root to: 'front#index'
end

app/models/request.rb
# frozen_string_literal: true

#
# == Schema Information
#
# Table name: requests
#
#  id          :integer          not null, primary key
#  homework_id :integer
#  user_id     :integer
#  accepted    :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_requests_on_homework_id  (homework_id)
#  index_requests_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (homework_id => homeworks.id)
#  fk_rails_...  (user_id => users.id)
#

class Request < ApplicationRecord
  has_many :messages, dependent: :destroy
  scope :accepted, -> { where accepted: true }

  belongs_to :homework
  belongs_to :user

  validates :homework, uniqueness: { scope: :user }

  after_create :notify_user

  after_update :homework_accepted, if: :accepted_changed?

  def notify_user
    HomeworkMailer.request_received(id).deliver_later
  end

  def notify_accepted
    HomeworkMailer.request_accepted(id).deliver_later
  end

  def homework_accepted
    homework.update accepted_request: self
    homework.request_accepted
    homework.save!
    homework.process_payment
  end
end

app/controllers/requests_controller.rb
# frozen_string_literal: true

class RequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_homework
  before_action :set_request, only: %i[show accept show]

  helper_method :homework, :collection, :homework_request

  def index
    @homework_request = collection.first
  end

  # GET /homeworks/1/requests/1
  def show
    render :index
  end

  # POST /homeworks/1/requests
  def create
    if homework.users << current_user
      redirect_to homework, notice: I18n.t('app.homeworks.requested')
    else
      redirect_to homework, error: I18n.t('app.homeworks.already_requested')
    end
  end

  def accept
    if homework.own?(current_user) && homework_request.update(accepted: true)
      redirect_to homework, notice: I18n.t('app.homeworks.accepted')
    else
      redirect_to homework, error: 'No autorizado'
    end
  end

  private

  attr_reader :homework, :homework_request

  def collection
    @collection ||= homework.own?(current_user) ? owner_collection : requester_collection
  end

  def owner_collection
    homework.requests.page(params[:page]).per(10)
  end

  def requester_collection
    homework.requests.where(user_id: current_user.id).page(params[:page]).per(10)
  end

  def set_request
    @homework_request = homework.requests.find(params[:id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_homework
    @homework = Homework.find(params[:homework_id])
  end
end

app/helpers/requests_helper.rb
# frozen_string_literal: true

module RequestsHelper
end

app/views/requests/_request.html.haml
.messages-wrapper
  .messages-body{conversation_id: request.id}
    = render request.messages

app/views/requests/index.html.haml
#application{class: "background #{random_background}"}
  #default_request{"data_request" => homework_request.id}
  .container.vertical-align.sign_up
    = render 'shared/flash'
    .row.homeworks-container
      .col-md-12.form
        .requests.col-md-3
          - if homework.in_progress?
            - homework.requests.accepted.each do |request|
              = link_to homework_request_path(homework, request), class: 'request-user' do
                = image_tag 'blank.png', class: 'homework-request', style: "background-image: url(#{request.user.avatar.url(:thumb)})"
                %strong
                  %p= request.user.username
                  %p Rating: user.rating
          - else
            - collection.each do |request|
              = link_to homework_request_path(homework, request), class: 'request-user' do
                = image_tag 'blank.png', class: 'homework-request', style: "background-image: url(#{request.user.avatar.url(:thumb)})"
                %strong
                  %p= request.user.username
                %p= "Rating: #{request.user.rating}"

          = paginate collection
        .chat_area.col-md-9
          - if homework.in_progress?
            = render homework.accepted_request
          - else
            = render homework_request

          = semantic_form_for [homework, homework_request, Message.new], remote: true do |f|
            = f.input :message, label: false, input_html: { rows: '2' }
            = f.actions do
              = f.submit 'Enviar Mensaje'
          - if homework.own?(current_user)
            - if homework.requests.accepted.empty?
              .accept_homework_section
                %p= "El usuario #{homework_request.user.username} ah solicitado hacer tu tarea, da click en Aceptar para asignarlo como consultor y empezara a hacer tu tarea una vez hallamos hecho el cobro correspondiente a tu tarjeta u Oxxo"
                = link_to 'Aceptar Solicitud', accept_homework_request_path(homework, homework_request), method: :post, class: 'estudex-button request', data: { confirm: t('app.homeworks.confirm_payment') }