config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :user do
    unauthenticated :user do
      root 'front#index', as: :front_page
    end

    authenticated :user do
      root 'homeworks#index', as: :authenticated_user_root
    end
  end

  get 'choose', to: 'choose_registration#new', as: :choose_registration
  post 'conekta_oxxo_pay' => 'oxxo_pay#received'

  resources :consultor_onboarding, only: [:new, :update], path_names: { new: 'first_step' } do
    member do
      post :add_accounts
    end
    collection do
      get :second_step
      get :third_step
      get :fourth_step
    end
  end
  resources :onboarding, except: [:index, :edit, :destroy], path_names: { new: 'first_step' } do
    member do
      get :second_step
      get :fourth_step
      get :fifth_step
      get :sixth_step
      patch :set_main_image
    end
  end
  resources :homeworks do
    member do
      post :process_payment
      put :publish
      delete :unpublish
    end
    resources :requests do
      resources :messages, only: :create
      member do
        post :accept
      end
    end
    resources :documents, only: [:index, :new, :create]
    resources :approvals, only: [:new, :create]
  end
  resources :cards, except: [:show, :edit, :update] do
    member do
      patch :make_default
    end
  end
  resources :bank_transfers, only: [:new, :create]
  resources :accounts, except: [:show, :index]

  mount LetterOpenerWeb::Engine, at: '/mails' if Rails.env.staging? || Rails.env.development?
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'

  root to: 'front#index'
end

app/models/onboarding.rb
# frozen_string_literal: true

class Onboarding
  include ActiveModel::Model
  attr_accessor :files
  validates :files, presence: true
end

app/controllers/onboarding_controller.rb
# frozen_string_literal: true

class OnboardingController < ApplicationController
  before_action :authenticate_user!
  before_action :set_homework, except: %i[index new create]

  helper_method :homework, :card

  def index
    redirect_to new_onboarding_path
  end

  def new
    @homework = current_user.homeworks.new
  end

  def show
    render :second_step
  end

  def create
    @homework = current_user.homeworks.new homework_params

    if homework.save
      redirect_to second_step_onboarding_path(homework)
    else
      render :new
    end
  end

  def second_step
  end

  def fourth_step
  end

  def fifth_step
  end

  def sixth_step
    @card = Card.new
  end

  def set_main_image
    redirect_to fourth_step_onboarding_path(homework) if homework.update(homework_params)
  end

  def update
    if homework.update(homework_params) && homework.publish! && homework.valid?
      current_user.update onboarding: false
      redirect_to after_onboarding_path(homework)
    else
      render :fourth_step
    end
  end

  private

  attr_reader :homework, :card

  def set_homework
    @homework = current_user.homeworks.find(params[:id])
  end

  def after_onboarding_path(homework = nil)
    return fifth_step_onboarding_path(homework) if current_user.cards.empty?
    homeworks_path
  end

  def homework_params
    params.require(:homework).permit(
      :name,
      :description,
      :price,
      :due_date,
      :category_id,
      :other_category,
      documents_attributes: [:file]
    )
  end
end

app/helpers/onboarding_helper.rb
# frozen_string_literal: true

module OnboardingHelper
  def link_to_cards
    next_url = current_user.cards.any? ? homeworks_path : sixth_step_onboarding_path

    link_to next_url, class: 'col-md-6' do
      image_tag 'blank.png', class: 'image-icon credit-card'
    end
  end
end

app/views/onboarding/fifth_step.html.haml
#onboarding{class: "background #{random_background}"}
  .container.vertical-align
    .row
      .col-md-6.col-md-push-3.form.text-center
        %h1= I18n.t('app.onboarding.step_5_title')
        %br

        = link_to homeworks_path, class: 'col-md-6' do
          = image_tag 'blank.png', class: 'image-icon oxxo'
        = link_to_cards
    .row
      .col-md-6.col-md-push-3.form.text-right
        = link_to 'Regresar', :back, class: 'col-md-2 col-md-push-10 text-center estudex-button'

app/views/onboarding/fourth_step.html.haml
#onboarding{class: "background #{random_background} expanded"}
  .container.vertical-align.sign_up
    .row
      .col-md-6.col-md-push-3.form.text-center
        %h2= I18n.t('app.onboarding.step_4_title')
        %br
        = semantic_form_for homework, url: onboarding_path(homework) do |f|
          = f.inputs do
            = f.input :name, required: true
            = f.input :description, input_html: { rows: 10, placeholder: 'Describenos lo que necesitas' }, required: true
            = f.input :due_date, as: :string, required: true, input_html: { data: { provide: 'datepicker', 'date-format' => "dd-mm-yyyy", placeholder: 'DD-MM-YYYY' }, autocomplete: 'off' }
            = f.input :price, required: true, input_html: { max: '10000', placeholder: 'Maximo $10,000 pesos' }
            = f.input :category, required: true
            = f.input :other_category, required: true, wrapper_html: { style: 'display: none;' }
          = f.actions do
            = f.submit I18n.t('app.onboarding.next')
            = f.action :cancel, label: 'Regresar'

app/views/onboarding/new.html.haml
#onboarding{class: "background #{random_background}"}
  .container.vertical-align
    .row
      .col-md-6.col-md-push-3.form.text-center
        %h1= I18n.t('app.onboarding.step_1_title')

        = semantic_form_for homework, url: onboarding_index_path do |f|
          = f.inputs do
            = f.input :name
          = f.actions do
            = f.submit I18n.t('app.onboarding.next')

app/views/onboarding/second_step.html.haml
#onboarding{class: "background #{random_background}"}
  .container.vertical-align
    .row
      .col-md-6.col-md-push-3.form.text-center
        %h2= I18n.t('app.onboarding.step_2_title')
        %br

        .hidden
          = semantic_form_for homework, url: set_main_image_onboarding_path(homework), method: :patch do |f|
            = f.inputs do
              = f.input :documents, as: :file, input_html: { name: 'homework[documents_attributes][0][file]' }
            = f.actions

        .row
          %a.col-md-6#upload_image{href: '#'} Documento, Foto, PDF

          = link_to 'Describenos tu Tarea', fourth_step_onboarding_path(homework), class: 'col-md-6'
    .row
      .col-md-6.col-md-push-3.form.text-right
        = link_to 'Regresar', :back, class: 'col-md-2 col-md-push-10 text-center estudex-button'

app/views/onboarding/sixth_step.html.haml
#onboarding{class: "background #{random_background} expanded"}
  .container.vertical-align.sign_up
    .row
      .col-md-6.col-md-push-3.form.text-center
        %h2= I18n.t('app.onboarding.step_6_title')

        = semantic_form_for card do |f|
          .card-errors
          = f.inputs do
            .row
              .col-md-12
                = f.input :name, placeholder: 'Gordolfo Gelatino'
            .row
              .col-md-12
                = f.input :number, as: :number, placeholder: '4242424242424242'
            .row
              .col-md-4
                = f.input :cvc, as: :number, placeholder: '123', input_html: { maxlength: 4  }
              .col-md-4
                = f.input :exp_month, as: :number, placeholder: '02', input_html: { maxlength: 2  }
              .col-md-4
                = f.input :year, as: :number, placeholder: '21', input_html: { maxlength: 2  }
                = f.input :add_card_page, as: :hidden, input_html: { value: request.env['HTTP_REFERER'] }

          = f.actions do
            = f.submit I18n.t('app.onboarding.next')
            = f.action :cancel, label: 'Regresar'